### ISSUE TITLE
pipes in unloaded/far-away blocks are dropping items on the ground

### ISSUE THREAD

**Issue by wischi-chr** [minetest-mods/pipeworks#116] opened 2015-07-25 02:30 UTC
steps to reproduce this
(with pipeworks and technic)
1. build HV quarry
2. go 100m / nodes away from the quarry and
   build a generator, switching-station and a chest there.
3. connect quarry, generator, switching-station with hv cable
4. connect quarry and chest with tubes (single line)
5. wait near the switching station for about 5-10min
6. walk back to the quarry -> there a some items on the ground.

Edit: (added Screenshot)
![pipe_bug](https://cloud.githubusercontent.com/assets/2495113/8889880/a16abe3e-32ec-11e5-93f7-0eb6439aacd4.png)

**Comment by Ekdohibs** [comment] 2015-07-25 12:31
Could you try with https://github.com/VanessaE/pipeworks/commit/bedcf4d6467c987a1ef29088d363f9cea1b095db please? It should fix the issue, I have however been unable to reproduce it, so I am not sure

**Comment by wischi-chr** [comment] 2015-07-25 14:48
Yes that fixed the item dropping. :+1:

Now if there are many items in a long tube (I think this happens when pipes try to pump into "ignore" nodes) the console is spammed with:

`ERROR[ServerThread]: ServerEnv: Trying to store id=2655 statically but block (0,1,-4) already contains 49 objects. Forcing delete.`

![pipe_bug_2](https://cloud.githubusercontent.com/assets/2495113/8889879/a169175a-32ec-11e5-8443-4ca014d26cde.png)

I don't know what minetest is trying to store in the block (entities? items?) so I'm not able to tell the problem is mod or engine related.

**Comment by asl97** [comment] 2015-07-25 14:58
@wischi-chr not that long ago on the irc, someone said that object in pipes aren't store by the engine but by the mod

if anything, i think it is cause item is being drop somewhere on the map.

**Comment by Ekdohibs** [comment] 2015-07-25 14:59
The problem is caused by pipeworks entities moving into unloaded blocks -- however, pipeworks doesn't want to store them as staticdata, since it already handles them. The problem is that minetest doesn't allow to just delete the entity when it gets unloaded, thus spamming the console with messages when these entities get store statically, and when there is no more room in the mapblock for static objects

**Comment by wischi-chr** [comment] 2015-07-25 15:11
@Ekdohibs but only the entities (visual representation) are deleted right? or will the item itself be deleted to?

**Comment by asl97** [comment] 2015-07-25 15:14
@wischi-chr the item itself too.

@Ekdohibs if that is the case, the only way of fixing this is when the engine has a way for mods to tell it not to save an entity isn't it?

maybe an on_deactivate funcion is needed.

someone would need to tell upstream about this issue by making an issue at [minetest](https://github.com/minetest/minetest/issues).

**Comment by wischi-chr** [comment] 2015-07-25 16:01
@asl97 I was not sure so i tested it. I injected 2 stacks of cobble itemwise into a very long pipe and waited for a bit (about 3min) -> tons of `Forcing delete.` messages. Then I collected the cobble back in: exactly 2 stacks. So non of the items were actually deleted.

Here a bunch of error messages I encountered during testing.
* `ERROR[ServerThread]: ServerEnv: Trying to store id=2619 statically but block (0,1,-4) already contains 49 objects. Forcing delete.`
* `WARNING: StaticObjectList::remove(): id=2957 not found`
* `ERROR[ServerThread]: ServerEnvironment::deactivateFarObjects(): id=3090 m_static_exists=true but static data doesn't actually exist in (0,1,-6)`

**Comment by Ekdohibs** [comment] 2015-07-25 16:03
@wischi-chr only the visual representation, since pipeworks uses entities only for visual representation and they are saved in a separate part of the code.

@asl97 there was once a pull request about it, it looks like it hasn't been merged, sadly.

**Comment by asl97** [comment] 2015-07-25 16:03
@wischi-chr it is deleted from the world but restore from pipewords saves

**Comment by Ekdohibs** [comment] 2015-07-25 16:06
@wischi-chr I'm almost sure the last two error messages are due to pipeworks removing the item in get_staticdata. You could try to comment https://github.com/VanessaE/pipeworks/blob/master/luaentity.lua#L290 and see if you still get those error messages, or only the first one.

**Comment by asl97** [comment] 2015-07-25 16:08
@Ekdohibs the only thing i can find on the issue tracker is that circuit simulator which has `on_deactivate` but it doesn't seem to have anything to do with object/entity.

**Comment by Ekdohibs** [comment] 2015-07-25 16:09
@asl97 https://github.com/minetest/minetest/pull/597

**Comment by wischi-chr** [comment] 2015-07-25 23:26
@Ekdohibs after commenting line 290
`parent:_remove_attached(self.attached_id)`

minetest crashes shortly after the world is loaded (1-3 seconds) with the following error message:
```
ERROR[main]: ServerError: ...ppData\Roaming\Minetest\bin\..\builtin\common\vector.lua:100: attempt to index local 'a' (a nil value)
ERROR[main]: stack traceback:
ERROR[main]: 	...ppData\Roaming\Minetest\bin\..\builtin\common\vector.lua:100: in function 'subtract'
ERROR[main]: 	...netest\bin\..\games\sub0815\mods\pipeworks/luaentity.lua:321: in function <...netest\bin\..\games\sub0815\mods\pipeworks/luaentity.lua:312>
ERROR[main]: 	...ppData\Roaming\Minetest\bin\..\builtin\game\register.lua:341: in function <...ppData\Roaming\Minetest\bin\..\builtin\game\register.lua:329>

```

**Comment by HybridDog** [comment] 2016-05-24 19:06
@Ekdohibs If you put this to the entity's definition, it gets removed when it becomes unloaded, doesn't it?
```
get_staticdata = function(self)
	self.object:remove()
end,```

**Comment by sofar** [comment] 2016-05-24 21:19
Yes, that would remove it, but may race or crash other code.

**Comment by Ekdohibs** [comment] 2016-07-15 20:49
@HybridDog That's what https://github.com/minetest/minetest/pull/597 was for; unfortunately it has been closed unmerged. As you can see, the idea was there since that code was written: https://github.com/minetest-mods/pipeworks/blob/master/luaentity.lua#L286 ; which was unfortunately on a tablet where I couldn't run MT: the code was written and only ever tested one month later, where I didn't make any changes except the bugs :/. Thus, this has to be tested; I think the very existence of the engine pull request shows it won't work.

**Comment by raymoo** [comment] 2017-09-03 16:08
There's  a new PR getting attention that allows entities to not be saved.

**Comment by asl97** [comment] 2017-09-04 02:24
@raymoo Your post would be more useful if you linked the PR.

Did you mean this PR https://github.com/minetest/minetest/pull/5112 ?

**Comment by raymoo** [comment] 2017-09-04 20:17
@asl97 Yes, sorry.

**Comment by VanessaE** [comment] 2018-06-06 11:53
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues

**Closed by VanessaE** 2018-06-06 11:53 UTC
Labels: bug
